### ISSUE TITLE
Can't install in comfy ui . 

### ISSUE THREAD

**Issue by ikly** [storyicon/comfyui_musev_evolved#1]
Can't install in comfy ui . 
Even if I practice all the guides on the git page, it’s useless and still marked in red. Repeating pip install -r requirements.txt is also useless. I would like to ask for improvements.

**Comment by giusparsifal** [comment]
Hello, after many attempts I finally can see the nodes MuseVPredictorV1 An MuseVImg2VidV1. Well, Everytime I have to try update from Manager to see the nodes but ok...
I thought evrything, finally, was ok but... here is the screeshot of error.
Can you help me, please?
Thanks
![Muse5](https://github.com/storyicon/comfyui_musev_evolved/assets/168450866/01c7cc65-ca43-4fd0-8301-4b44f8c285f8)

**Comment by ProtoBelisarius** [comment]
You can't really ask for improvements if you don't actually describe your problem.

What error messages are you getting in the terminal or comfy?

If its a problem mentioning xformers and you do not have an nvidia card, then you are currently stuck. It seems the original code requires xformers and Im unsure if its possible to rewrite it.

**Comment by ikly** [comment]
<img width="1049" alt="스크린샷 2024-06-02 011210" src="https://github.com/storyicon/comfyui_musev_evolved/assets/55575896/8d087e9f-f921-4dd9-92c0-142f0e4016fe">
No matter how hard I try, I can't see the node, only the red node. I've even checked the diffuser folder as described in the installation page

<img width="543" alt="스크린샷 2024-06-02 011415" src="https://github.com/storyicon/comfyui_musev_evolved/assets/55575896/628fd4f4-d052-402e-a7c4-10fb72689eed">
<img width="584" alt="스크린샷 2024-06-02 011443" src="https://github.com/storyicon/comfyui_musev_evolved/assets/55575896/015470cc-bd5b-4d0e-87cc-6e68772f57f0">


The cmd simply says that the node was not found.
<img width="854" alt="스크린샷 2024-06-02 011343" src="https://github.com/storyicon/comfyui_musev_evolved/assets/55575896/2dcb37e7-bb2d-45c9-acab-939ad7926ff5">
